name: "Sample"
on:
  workflow_dispatch:

 
jobs:
  Image_Version_Validation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: docker pull
        run: |
          docker pull ghcr.io/svarvindh/github-actions-approval:latest

#       - uses: svarvindh/github-actions-approval@v8.0.0
#         id: bypass
#         with:
#           secret: ${{ secrets.GITHUB_TOKEN }}
#           approvers: svarvindh
#           minimum-approvals: 1
#           issue-title: "Approval to bypass"
  
#       - name: Dummy Proceed to deployment
#         id: deploy
#         run: |
#           echo ${{ steps.bypass.outputs.status }}
