name: "Sample"
on:
  workflow_dispatch:

jobs:
  Image_Version_Validation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: echos
        run: |
          docker version
          go version
          docker run -t -i -e GITHUB_REPOSITORY='svarvindh/samples' \
          -e GITHUB_RUN_ID='5251184449' \
          -e GITHUB_REPOSITORY_OWNER='svarvindh' \
          -e INPUT_SECRET='${{ secrets.TOKEN }}' \
          -e INPUT_APPROVERS='svarvindh' ghcr.io/svarvindh/gha-approval:latest
          
      - uses: svarvindh/gha-approval@v3.0.0
        id: bypass
        with:
          secret: ${{ secrets.TOKEN }}
          approvers: svarvindh
          minimum-approvals: 1
          issue-title: "Approval to bypass"
  
  
      - name: Dummy Proceed to deployment
        id: deploy
        run: |
          echo ${{ steps.bypass.outputs.status }}
